"""
AutoFlow AI X — Workflow DSL Pydantic Schema
=============================================

The DSL (Domain-Specific Language) is the canonical, executable representation
of a workflow inside AutoFlow AI X. Every workflow — whether generated by the
AI planner, built in the visual editor, or created via API — is stored and
executed as a DSL JSON object.

Template variable syntax: {{node_id.output.field}}, {{trigger.payload.field}},
                           {{context.today}}, {{env.VAR_NAME}}
"""

import re
import uuid
from enum import Enum
from typing import Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, Field, field_validator, model_validator


# ─────────────────────────────────────────────────────────────────────────────
# ENUMS
# ─────────────────────────────────────────────────────────────────────────────

class TriggerType(str, Enum):
    schedule  = "schedule"    # Cron-based scheduling (APScheduler)
    webhook   = "webhook"     # Incoming HTTP POST to /hooks/{workflow_id}
    manual    = "manual"      # Triggered by user or API call
    event     = "event"       # Internal AutoFlow event bus


class NodeType(str, Enum):
    trigger     = "trigger"       # Entry point — exactly one per workflow
    action      = "action"        # Performs an external operation
    condition   = "condition"     # Branches flow based on a boolean expression
    delay       = "delay"         # Pauses execution for a duration
    loop        = "loop"          # Iterates over a list of items
    ai_agent    = "ai_agent"      # Calls an LLM for reasoning or text generation
    transformer = "transformer"   # Reshapes/maps data between nodes


class ServiceType(str, Enum):
    # Communication
    gmail          = "gmail"
    whatsapp       = "whatsapp"
    slack          = "slack"
    twilio         = "twilio"          # SMS / voice

    # Google Workspace
    google_sheets  = "google_sheets"
    google_calendar = "google_calendar"
    google_drive   = "google_drive"

    # CRMs
    hubspot        = "hubspot"
    salesforce     = "salesforce"

    # Productivity
    notion         = "notion"
    airtable       = "airtable"

    # HTTP / Webhooks
    http           = "http"            # Generic HTTP request

    # AI
    openai         = "openai"
    groq           = "groq"

    # Built-in AutoFlow operations
    builtin        = "builtin"         # Condition, loop, delay, transformer

    # Scheduling
    scheduler      = "scheduler"       # Internal trigger service


class OperationType(str, Enum):
    # Gmail
    send_email         = "send_email"
    get_emails         = "get_emails"
    create_draft       = "create_draft"

    # Google Sheets
    read_rows          = "read_rows"
    append_row         = "append_row"
    update_row         = "update_row"
    find_row           = "find_row"

    # Google Calendar
    create_event       = "create_event"
    list_events        = "list_events"

    # WhatsApp / Twilio
    send_message       = "send_message"
    send_sms           = "send_sms"

    # Slack
    post_message       = "post_message"

    # HTTP
    http_request       = "http_request"

    # AI
    llm_generate       = "llm_generate"
    llm_classify       = "llm_classify"
    llm_extract        = "llm_extract"

    # Built-in
    condition_branch   = "condition_branch"
    for_each           = "for_each"
    wait               = "wait"
    map_fields         = "map_fields"
    filter_list        = "filter_list"
    set_variable       = "set_variable"

    # Trigger operations
    cron               = "cron"
    webhook_listen     = "webhook_listen"
    manual_trigger     = "manual_trigger"


# ─────────────────────────────────────────────────────────────────────────────
# TRIGGER CONFIG (discriminated union)
# ─────────────────────────────────────────────────────────────────────────────

class ScheduleTriggerConfig(BaseModel):
    cron: str = Field(..., description="Cron expression e.g. '0 9 * * *'")
    timezone: str = Field(default="UTC")

    @field_validator("cron")
    @classmethod
    def validate_cron(cls, v: str) -> str:
        parts = v.strip().split()
        if len(parts) not in (5, 6):
            raise ValueError(f"Invalid cron expression '{v}': must have 5 or 6 fields.")
        return v


class WebhookTriggerConfig(BaseModel):
    path: Optional[str] = Field(None, description="Custom webhook path slug")
    secret: Optional[str] = Field(None, description="HMAC signature secret for verification")
    method: str = Field(default="POST")


class ManualTriggerConfig(BaseModel):
    description: Optional[str] = None


class EventTriggerConfig(BaseModel):
    event_name: str = Field(..., description="Internal AutoFlow event name to listen for")
    filters: Optional[Dict[str, Any]] = None


class TriggerConfig(BaseModel):
    type: TriggerType
    config: Union[
        ScheduleTriggerConfig,
        WebhookTriggerConfig,
        ManualTriggerConfig,
        EventTriggerConfig,
        Dict[str, Any],   # fallback for LLM-generated configs
    ] = Field(default_factory=dict)


# ─────────────────────────────────────────────────────────────────────────────
# RETRY POLICY
# ─────────────────────────────────────────────────────────────────────────────

class RetryPolicy(BaseModel):
    max_attempts: int = Field(default=3, ge=1, le=10)
    backoff_seconds: int = Field(default=60, ge=0)
    backoff_multiplier: float = Field(default=2.0, ge=1.0)


# ─────────────────────────────────────────────────────────────────────────────
# WORKFLOW NODE
# ─────────────────────────────────────────────────────────────────────────────

class WorkflowNodeDSL(BaseModel):
    id: str = Field(
        ...,
        description="Unique node ID within this workflow. Use snake_case (e.g. 'send_email_1').",
        pattern=r"^[a-z][a-z0-9_]*$",
    )
    type: NodeType
    service: ServiceType
    operation: OperationType
    label: str = Field(..., description="Human-readable name shown in the visual editor")

    # Template-variable-aware parameters specific to this operation
    params: Dict[str, Any] = Field(
        default_factory=dict,
        description=(
            "Operation-specific parameters. Supports template vars: "
            "{{node_id.output.field}}, {{trigger.payload.field}}, {{context.today}}, {{env.VAR}}"
        ),
    )

    # Routing
    on_success: Optional[str] = Field(
        None,
        description="Node ID to route to when this node completes successfully.",
    )
    on_failure: Optional[str] = Field(
        None,
        description="Node ID to route to when this node fails. Null = stop and mark run failed.",
    )

    # Optional per-node overrides
    retry_policy: Optional[RetryPolicy] = None
    timeout_seconds: Optional[int] = Field(None, ge=1, le=3600)
    is_disabled: bool = Field(default=False)

    @field_validator("id")
    @classmethod
    def id_no_reserved_names(cls, v: str) -> str:
        reserved = {"start", "end", "true", "false", "null", "none"}
        if v.lower() in reserved:
            raise ValueError(f"Node ID '{v}' is a reserved keyword.")
        return v


# ─────────────────────────────────────────────────────────────────────────────
# WORKFLOW EDGE
# ─────────────────────────────────────────────────────────────────────────────

class WorkflowEdgeDSL(BaseModel):
    source_id: str = Field(..., description="ID of the source node")
    target_id: str = Field(..., description="ID of the target node")
    label: Optional[str] = Field(
        None,
        description="Edge label shown on canvas. For condition nodes: 'true' | 'false' | custom.",
    )
    condition: Optional[str] = Field(
        None,
        description=(
            "Optional Jinja2-style boolean expression evaluated at runtime. "
            "If present, the edge is only traversed when the expression is truthy. "
            "Example: \"{{node_2.output.count > 0}}\""
        ),
    )

    @model_validator(mode="after")
    def no_self_loop(self) -> "WorkflowEdgeDSL":
        if self.source_id == self.target_id:
            raise ValueError(f"Self-loop detected on node '{self.source_id}'.")
        return self


# ─────────────────────────────────────────────────────────────────────────────
# ROOT DSL OBJECT
# ─────────────────────────────────────────────────────────────────────────────

class WorkflowDSL(BaseModel):
    """
    The canonical, executable DSL representation of a workflow.
    This object is stored as `dsl_json` in the `workflows` DB table
    and is the single source of truth for the execution engine.
    """
    id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Workflow UUID (auto-generated if omitted)",
    )
    name: str = Field(..., min_length=1, max_length=255)
    description: Optional[str] = None
    version: int = Field(default=1, ge=1)
    industry: Optional[str] = Field(None, description="Industry context, e.g. 'healthcare'")
    trigger: TriggerConfig
    nodes: List[WorkflowNodeDSL] = Field(..., min_length=1)
    edges: List[WorkflowEdgeDSL] = Field(default_factory=list)

    # Metadata
    tags: List[str] = Field(default_factory=list)
    variables: Dict[str, Any] = Field(
        default_factory=dict,
        description="Workflow-level variables available as {{vars.key}} in all nodes",
    )

    @model_validator(mode="after")
    def validate_graph_references(self) -> "WorkflowDSL":
        """Ensure all edge references point to existing node IDs."""
        node_ids = {n.id for n in self.nodes}

        for edge in self.edges:
            if edge.source_id not in node_ids:
                raise ValueError(
                    f"Edge references unknown source node '{edge.source_id}'. "
                    f"Known nodes: {sorted(node_ids)}"
                )
            if edge.target_id not in node_ids:
                raise ValueError(
                    f"Edge references unknown target node '{edge.target_id}'. "
                    f"Known nodes: {sorted(node_ids)}"
                )

        # Validate on_success / on_failure references
        for node in self.nodes:
            if node.on_success and node.on_success not in node_ids:
                raise ValueError(
                    f"Node '{node.id}' has on_success='{node.on_success}' "
                    f"which does not exist."
                )
            if node.on_failure and node.on_failure not in node_ids:
                raise ValueError(
                    f"Node '{node.id}' has on_failure='{node.on_failure}' "
                    f"which does not exist."
                )

        return self

    @model_validator(mode="after")
    def validate_trigger_node(self) -> "WorkflowDSL":
        """Ensure exactly one trigger node exists."""
        trigger_nodes = [n for n in self.nodes if n.type == NodeType.trigger]
        if len(trigger_nodes) != 1:
            raise ValueError(
                f"Workflow must have exactly 1 trigger node, found {len(trigger_nodes)}."
            )
        return self

    @model_validator(mode="after")
    def validate_no_duplicate_node_ids(self) -> "WorkflowDSL":
        ids = [n.id for n in self.nodes]
        dupes = {i for i in ids if ids.count(i) > 1}
        if dupes:
            raise ValueError(f"Duplicate node IDs found: {dupes}")
        return self

    def to_db_dict(self) -> dict:
        """Serialize to a plain dict suitable for storing in JSONB."""
        return self.model_dump(mode="json")
